/**
 * Phase 48: JARVIS 用語辞典（完全ローカル）。
 * 各指標の初心者向け説明・JARVIS基準（色分けバンド）・注意点を集約。
 * 投資助言ではなく判断補助の参考情報。HelpTooltip / /help の単一データ源。
 */

export type RangeTone = "good" | "info" | "caution" | "danger";

export interface RangeBand {
  range: string;
  meaning: string;
  tone: RangeTone;
}

export interface GlossaryTerm {
  key: string;
  label: string;
  shortDescription: string;
  beginnerDescription: string;
  jarvisRange: RangeBand[];
  goodRange?: string;
  cautionRange?: string;
  dangerRange?: string;
  example?: string;
  warning?: string;
  relatedTerms: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  {
    key: "per",
    label: "PER",
    shortDescription: "株価が利益の何倍まで買われているか。",
    beginnerDescription: "株価 ÷ 1株利益。会社の稼ぐ力に対して株価が割高か割安かを測る、最も基本的な指標です。",
    jarvisRange: [
      { range: "15倍以下", meaning: "割安候補", tone: "good" },
      { range: "15〜40倍", meaning: "標準〜成長期待", tone: "info" },
      { range: "40〜70倍", meaning: "高期待・要確認", tone: "caution" },
      { range: "70倍以上", meaning: "過熱注意", tone: "danger" },
    ],
    goodRange: "15倍以下",
    cautionRange: "40〜70倍",
    dangerRange: "70倍以上",
    example: "PER 12倍なら、利益12年分で株価に達する水準。同業種と比べて判断します。",
    warning: "成長株では高PERでも許容される場合があります。赤字企業ではPERは意味を持ちません。",
    relatedTerms: ["pbr", "roe"],
  },
  {
    key: "pbr",
    label: "PBR",
    shortDescription: "株価が純資産の何倍か。",
    beginnerDescription: "株価 ÷ 1株純資産。会社の資産価値に対して株価が何倍かを示します。1倍が解散価値の目安です。",
    jarvisRange: [
      { range: "1倍未満", meaning: "割安候補", tone: "good" },
      { range: "1〜3倍", meaning: "標準", tone: "info" },
      { range: "3〜10倍", meaning: "成長期待", tone: "caution" },
      { range: "10倍以上", meaning: "高期待・過熱注意", tone: "danger" },
    ],
    goodRange: "1倍未満",
    cautionRange: "3〜10倍",
    dangerRange: "10倍以上",
    example: "PBR 0.8倍は、理論上の解散価値より株価が安い状態。ただし割安には理由がある場合も。",
    warning: "PBRが低いだけでは買い判断になりません。収益性（ROE）と併せて見ます。",
    relatedTerms: ["per", "roe"],
  },
  {
    key: "roe",
    label: "ROE",
    shortDescription: "自己資本でどれだけ利益を出しているか。",
    beginnerDescription: "利益 ÷ 自己資本。株主のお金をどれだけ効率よく利益に変えたかを示す収益効率の指標です。",
    jarvisRange: [
      { range: "10%未満", meaning: "弱い", tone: "caution" },
      { range: "10〜15%", meaning: "標準", tone: "info" },
      { range: "15〜25%", meaning: "優秀", tone: "good" },
      { range: "25%以上", meaning: "非常に優秀", tone: "good" },
    ],
    goodRange: "15%以上",
    cautionRange: "10%未満",
    example: "ROE 20%は、自己資本100に対し20の利益を生む優良企業の目安。",
    warning: "過度な借入（レバレッジ）でROEが高く見える場合があります。負債とセットで確認を。",
    relatedTerms: ["per", "pbr"],
  },
  {
    key: "rsi",
    label: "RSI",
    shortDescription: "買われすぎ・売られすぎを見る指標。",
    beginnerDescription: "一定期間の値動きから、買われすぎ／売られすぎを0〜100で示します。過熱感を測るのに使います。",
    jarvisRange: [
      { range: "30未満", meaning: "売られすぎ", tone: "good" },
      { range: "40〜65", meaning: "押し目候補", tone: "info" },
      { range: "65〜75", meaning: "強いが注意", tone: "caution" },
      { range: "80以上", meaning: "過熱注意", tone: "danger" },
    ],
    goodRange: "40〜65",
    cautionRange: "65〜75",
    dangerRange: "80以上",
    example: "RSI 82は買われすぎ圏。ここでの飛びつき買いは高値掴みのリスクが高い状態。",
    warning: "強いトレンドではRSIが高値に張り付くこともあります。単独では判断しないこと。",
    relatedTerms: ["macd", "volume"],
  },
  {
    key: "volume",
    label: "出来高",
    shortDescription: "その株がどれだけ売買されたか。",
    beginnerDescription: "成立した売買株数です。関心の強さや、相場の転換点を読むのに使います。急増は要注目のサイン。",
    jarvisRange: [
      { range: "20日平均の1.5倍以上", meaning: "注目", tone: "info" },
      { range: "2倍以上", meaning: "資金流入候補", tone: "good" },
      { range: "3倍以上", meaning: "急騰・急落注意", tone: "danger" },
    ],
    goodRange: "20日平均の2倍以上",
    dangerRange: "20日平均の3倍以上",
    example: "普段10万株が急に35万株に増えたら、大きな材料や転換のサインかもしれません。",
    warning: "高RSI＋出来高急増は天井圏の過熱サインの可能性。飛びつきに注意。",
    relatedTerms: ["rsi", "macd"],
  },
  {
    key: "macd",
    label: "MACD",
    shortDescription: "トレンド転換のタイミングを読む指標。",
    beginnerDescription: "2本の移動平均線の差から、上昇・下降への転換タイミングを読みます。線の交差（クロス）に注目します。",
    jarvisRange: [
      { range: "ゴールデンクロス", meaning: "上昇転換の目安", tone: "good" },
      { range: "0ラインより上", meaning: "上昇基調", tone: "info" },
      { range: "0ラインより下", meaning: "下降基調", tone: "caution" },
      { range: "デッドクロス", meaning: "下落転換の目安", tone: "danger" },
    ],
    example: "MACDがシグナル線を下から上に抜ける（ゴールデンクロス）と、上昇転換のサインとされます。",
    warning: "遅行指標のため、サインが出た時には動きが進んでいることも。だましも起こります。",
    relatedTerms: ["rsi", "volume"],
  },
  {
    key: "cagr",
    label: "CAGR",
    shortDescription: "複利ベースの年平均成長率。",
    beginnerDescription: "期間全体の成績を、複利で「1年あたり何%成長したか」にならした値です。長期の比較に使います。",
    jarvisRange: [
      { range: "0%未満", meaning: "低調", tone: "danger" },
      { range: "0〜5%", meaning: "緩やか", tone: "caution" },
      { range: "5〜15%", meaning: "良好", tone: "good" },
      { range: "15%以上", meaning: "優秀（過去実績）", tone: "good" },
    ],
    goodRange: "5〜15%",
    dangerRange: "0%未満",
    example: "3年で1.4倍なら CAGR 約12%。単純平均ではなく複利で計算します。",
    warning: "過去のCAGRは将来を保証しません。バックテストの数値は実運用と乖離することがあります。",
    relatedTerms: ["pf", "dd"],
  },
  {
    key: "pf",
    label: "PF",
    shortDescription: "総利益 ÷ 総損失（プロフィットファクター）。",
    beginnerDescription: "勝ちトレードの合計利益を、負けトレードの合計損失で割った値。1を超えると勝ち越しです。",
    jarvisRange: [
      { range: "1未満", meaning: "負け越し", tone: "danger" },
      { range: "1〜1.5", meaning: "やや優位", tone: "caution" },
      { range: "1.5〜2", meaning: "良好", tone: "good" },
      { range: "2以上", meaning: "優秀", tone: "good" },
    ],
    goodRange: "1.5以上",
    dangerRange: "1未満",
    example: "総利益30万・総損失15万なら PF 2.0。損失の2倍を稼げている状態。",
    warning: "取引回数が少ないとPFは安定しません。サンプル数と併せて評価します。",
    relatedTerms: ["cagr", "dd"],
  },
  {
    key: "dd",
    label: "DD",
    shortDescription: "直近ピークからの下落幅（ドローダウン）。",
    beginnerDescription: "資産が過去最高値からどれだけ落ち込んだかの割合です。最大DDは最悪期の落ち込み幅を示します。",
    jarvisRange: [
      { range: "10%以内", meaning: "軽微", tone: "good" },
      { range: "10〜20%", meaning: "許容範囲", tone: "info" },
      { range: "20〜35%", meaning: "要注意", tone: "caution" },
      { range: "35%以上", meaning: "大きい", tone: "danger" },
    ],
    goodRange: "10%以内",
    cautionRange: "20〜35%",
    dangerRange: "35%以上",
    example: "最大DD 30%は、一時的に資産が3割減った局面があったということ。精神的な耐性も要ります。",
    warning: "許容できる最大DDを事前に決めておくと、暴落時の狼狽売りを防げます。",
    relatedTerms: ["var", "cagr"],
  },
  {
    key: "var",
    label: "VaR",
    shortDescription: "一定確率で起こりうる想定最大損失。",
    beginnerDescription: "「95%の確率で、損失はこの金額（または%）以内に収まる」というリスクの大きさを示す推定値です。",
    jarvisRange: [
      { range: "資産の5%以内", meaning: "小さい", tone: "good" },
      { range: "5〜10%", meaning: "標準", tone: "info" },
      { range: "10〜20%", meaning: "大きい", tone: "caution" },
      { range: "20%以上", meaning: "非常に大きい", tone: "danger" },
    ],
    goodRange: "資産の5%以内",
    dangerRange: "資産の20%以上",
    example: "1日VaRが資産の8%なら、通常時の1日の損失はおおむね8%以内に収まる想定。",
    warning: "VaRは想定内のリスクの目安。暴落など想定外（テールリスク）はこれを超えます。",
    relatedTerms: ["dd", "montecarlo"],
  },
  {
    key: "montecarlo",
    label: "Monte Carlo",
    shortDescription: "乱数で多数の将来シナリオを試算する手法。",
    beginnerDescription: "値動きの特徴をもとに何千通りもの将来を乱数でシミュレーションし、破産確率や資産分布を推定します。",
    jarvisRange: [
      { range: "破産確率 1%未満", meaning: "健全", tone: "good" },
      { range: "1〜5%", meaning: "許容", tone: "info" },
      { range: "5〜10%", meaning: "注意", tone: "caution" },
      { range: "10%以上", meaning: "危険", tone: "danger" },
    ],
    goodRange: "破産確率 1%未満",
    dangerRange: "破産確率 10%以上",
    example: "1万回のシミュレーションで50回が破産→破産確率0.5%、という読み方をします。",
    warning: "入力した前提（リターン・変動率）が現実と違えば結果も変わります。あくまで推定です。",
    relatedTerms: ["var", "dd"],
  },
  {
    key: "factor",
    label: "Factor",
    shortDescription: "リターンの源泉を要因に分解する分析。",
    beginnerDescription: "リターンをバリュー・モメンタム・サイズなどの「要因」に分解し、成績がどこから来ているかを分析します。",
    jarvisRange: [
      { range: "バリュー", meaning: "割安さで買う要因", tone: "info" },
      { range: "モメンタム", meaning: "勢いに乗る要因", tone: "info" },
      { range: "サイズ", meaning: "企業規模による要因", tone: "info" },
      { range: "偏り過大", meaning: "1要因依存に注意", tone: "caution" },
    ],
    example: "成績の大半がモメンタム由来なら、相場の勢いが止まると弱くなる傾向がある、と読めます。",
    warning: "特定要因に偏りすぎると、その要因が不調な局面で一気に崩れます。分散を意識します。",
    relatedTerms: ["riskgrade", "cagr"],
  },
  {
    key: "riskgrade",
    label: "Risk Grade",
    shortDescription: "ポートフォリオ全体のリスク総合評価（A〜D）。",
    beginnerDescription: "集中度・変動の大きさなどから、資産全体のリスクをA〜Dで評価した本アプリ独自の指標です。",
    jarvisRange: [
      { range: "A", meaning: "低リスク", tone: "good" },
      { range: "B", meaning: "標準", tone: "info" },
      { range: "C", meaning: "やや高い", tone: "caution" },
      { range: "D", meaning: "高リスク", tone: "danger" },
    ],
    goodRange: "A",
    dangerRange: "D",
    example: "Grade D は集中しすぎ・変動が大きすぎのサイン。現金比率↑・分散↑を検討します。",
    warning: "Grade Dの警告は放置しないこと。防御的な配分への見直しを優先します。",
    relatedTerms: ["var", "disciplinescore"],
  },
  {
    key: "disciplinescore",
    label: "Discipline Score",
    shortDescription: "売買ルールの遵守度を点数化した指標。",
    beginnerDescription: "損切り・保有比率など自分で決めたルールをどれだけ守れているかを点数化した本アプリ独自の指標です。",
    jarvisRange: [
      { range: "90以上", meaning: "良好", tone: "good" },
      { range: "50〜89", meaning: "改善余地", tone: "caution" },
      { range: "50未満", meaning: "要改善", tone: "danger" },
    ],
    goodRange: "90以上",
    dangerRange: "50未満",
    example: "損切りルールを破った取引が続くとスコアが下がります。感情的売買の抑止に使います。",
    warning: "スコアが低い時は取引額を落とし、まずルール遵守を取り戻すことを優先します。",
    relatedTerms: ["riskgrade"],
  },
  {
    key: "adaptivescore",
    label: "Adaptive Score",
    shortDescription: "相場環境に応じて重み付けを調整する応用スコア。",
    beginnerDescription: "JARVIS Score を基に、地合い（強気/弱気）やリスク状況に応じて各指標の重みを動的に調整した発展版スコアです。",
    jarvisRange: [
      { range: "80以上", meaning: "有力", tone: "good" },
      { range: "60〜80", meaning: "標準", tone: "info" },
      { range: "40〜60", meaning: "中立", tone: "caution" },
      { range: "40未満", meaning: "弱い", tone: "danger" },
    ],
    goodRange: "80以上",
    dangerRange: "40未満",
    example: "弱気相場ではディフェンシブ寄りの指標が重くなり、同じ銘柄でもスコアが変わります。",
    warning: "基礎スコア同様、単独で売買判断せず判断補助として使います。",
    relatedTerms: ["factorcontribution", "riskgrade"],
  },
  {
    key: "factorcontribution",
    label: "Factor Contribution",
    shortDescription: "各ファクターがリターンにどれだけ寄与したか。",
    beginnerDescription: "リターンの源泉を Growth / Value / Quality などの要因に分解し、それぞれがどれだけ効いたか（寄与度）を示します。",
    jarvisRange: [
      { range: "プラス寄与", meaning: "好影響", tone: "good" },
      { range: "ほぼ中立", meaning: "影響小", tone: "info" },
      { range: "マイナス寄与", meaning: "逆風", tone: "caution" },
    ],
    example: "成績の大半が Momentum 由来なら、勢いが止まると弱くなる傾向がある、と読めます。",
    warning: "特定ファクターへの偏りは、その要因が不調な局面で一気に弱くなります。",
    relatedTerms: ["growthfactor", "valuefactor", "qualityfactor", "momentumfactor"],
  },
  {
    key: "growthfactor",
    label: "Growth Factor",
    shortDescription: "売上・利益の成長性に着目する要因。",
    beginnerDescription: "企業の成長スピード（増収増益）に注目する投資要因です。伸びる会社に賭ける考え方。",
    jarvisRange: [
      { range: "高い", meaning: "成長期待", tone: "good" },
      { range: "標準", meaning: "平均的", tone: "info" },
      { range: "低い", meaning: "成長鈍化", tone: "caution" },
    ],
    warning: "高成長株はPERが割高になりやすく、期待を外すと下落幅も大きくなります。",
    relatedTerms: ["valuefactor", "qualityfactor"],
  },
  {
    key: "valuefactor",
    label: "Value Factor",
    shortDescription: "割安さ（PER/PBR等）に着目する要因。",
    beginnerDescription: "利益や資産に対して株価が割安な銘柄を狙う投資要因です。安く買って見直しを待つ考え方。",
    jarvisRange: [
      { range: "割安", meaning: "妙味あり", tone: "good" },
      { range: "標準", meaning: "適正圏", tone: "info" },
      { range: "割高", meaning: "妙味薄い", tone: "caution" },
    ],
    warning: "割安には理由がある場合も（バリュートラップ）。収益性と併せて確認します。",
    relatedTerms: ["growthfactor", "qualityfactor", "per"],
  },
  {
    key: "qualityfactor",
    label: "Quality Factor",
    shortDescription: "収益性・財務健全性の質に着目する要因。",
    beginnerDescription: "ROEの高さや財務の健全さなど、企業の「質」に注目する投資要因です。丈夫な会社を選ぶ考え方。",
    jarvisRange: [
      { range: "高品質", meaning: "優良", tone: "good" },
      { range: "標準", meaning: "平均的", tone: "info" },
      { range: "低品質", meaning: "要注意", tone: "caution" },
    ],
    warning: "高品質でも割高だと投資妙味は薄くなります。バリューと併せて見ます。",
    relatedTerms: ["valuefactor", "roe"],
  },
  {
    key: "momentumfactor",
    label: "Momentum Factor",
    shortDescription: "価格の勢い・トレンドに着目する要因。",
    beginnerDescription: "上昇の勢いが続く銘柄に乗る投資要因です。強いものはさらに強い、という考え方。",
    jarvisRange: [
      { range: "強い上昇", meaning: "順風", tone: "good" },
      { range: "横ばい", meaning: "中立", tone: "info" },
      { range: "下落", meaning: "逆風", tone: "danger" },
    ],
    warning: "勢いは急反転しやすく、天井掴みのリスクがあります。RSIの過熱と併用を。",
    relatedTerms: ["rsi", "macd"],
  },
  {
    key: "riskfactor",
    label: "Risk Factor",
    shortDescription: "変動性・下方リスクに着目する要因。",
    beginnerDescription: "値動きの荒さ（ボラティリティ）や下落リスクに注目する要因です。守りの観点を測ります。",
    jarvisRange: [
      { range: "低リスク", meaning: "安定", tone: "good" },
      { range: "標準", meaning: "平均的", tone: "info" },
      { range: "高リスク", meaning: "変動大", tone: "danger" },
    ],
    warning: "高リスクは高リターンと表裏一体。許容度に見合うかを確認します。",
    relatedTerms: ["var", "dd"],
  },
  {
    key: "disciplinefactor",
    label: "Discipline Factor",
    shortDescription: "規律遵守がリターンに与える寄与。",
    beginnerDescription: "損切りやルール遵守など、規律の高さが成績にどれだけ寄与したかを示す要因です。",
    jarvisRange: [
      { range: "高遵守", meaning: "好影響", tone: "good" },
      { range: "標準", meaning: "平均的", tone: "info" },
      { range: "低遵守", meaning: "悪影響", tone: "danger" },
    ],
    warning: "規律の乱れは短期では見えにくく、長期成績を静かに蝕みます。",
    relatedTerms: ["disciplinescore"],
  },
  {
    key: "rebalance",
    label: "Rebalance",
    shortDescription: "偏った保有比率を調整し分散を保つこと。",
    beginnerDescription: "値上がりで比率が膨らんだ銘柄を減らし、目標配分へ戻す作業です。集中リスクの是正に使います。",
    jarvisRange: [
      { range: "乖離 小", meaning: "維持でOK", tone: "good" },
      { range: "乖離 中", meaning: "調整検討", tone: "caution" },
      { range: "乖離 大", meaning: "要調整", tone: "danger" },
    ],
    warning: "頻繁な調整は手数料・税負担を増やします。閾値を決めて実行します。",
    relatedTerms: ["targetweight", "currentweight"],
  },
  {
    key: "targetweight",
    label: "Target Weight",
    shortDescription: "各銘柄の目標保有比率。",
    beginnerDescription: "ポートフォリオ内で各銘柄をどの比率にしたいか、という理想の配分です。",
    jarvisRange: [
      { range: "1銘柄 20%以内", meaning: "分散の目安", tone: "good" },
      { range: "20〜40%", meaning: "やや集中", tone: "caution" },
      { range: "40%超", meaning: "集中しすぎ", tone: "danger" },
    ],
    warning: "目標は固定ではなく、相場や方針に応じて定期的に見直します。",
    relatedTerms: ["currentweight", "rebalance"],
  },
  {
    key: "currentweight",
    label: "Current Weight",
    shortDescription: "現在の実際の保有比率。",
    beginnerDescription: "いま各銘柄がポートフォリオに占めている実際の比率です。目標との差がリバランスの対象になります。",
    jarvisRange: [
      { range: "目標近辺", meaning: "良好", tone: "good" },
      { range: "やや乖離", meaning: "監視", tone: "caution" },
      { range: "大きく乖離", meaning: "調整対象", tone: "danger" },
    ],
    warning: "上昇した銘柄は放置すると自然に比率が膨らみ、集中リスクになります。",
    relatedTerms: ["targetweight", "rebalance"],
  },
  {
    key: "expectedimpact",
    label: "Expected Impact",
    shortDescription: "提案実行時の期待リターンへの影響。",
    beginnerDescription: "そのリバランス提案を実行した場合に、期待リターンがどう変わるかの推定です。",
    jarvisRange: [
      { range: "プラス", meaning: "改善見込み", tone: "good" },
      { range: "中立", meaning: "ほぼ変化なし", tone: "info" },
      { range: "マイナス", meaning: "低下見込み", tone: "caution" },
    ],
    warning: "期待値は過去データを前提とした推定で、確実な予測ではありません。",
    relatedTerms: ["riskimpact", "rebalance"],
  },
  {
    key: "riskimpact",
    label: "Risk Impact",
    shortDescription: "提案実行時のリスクへの影響。",
    beginnerDescription: "そのリバランス提案を実行した場合に、ポートフォリオのリスクがどう変わるかの推定です。",
    jarvisRange: [
      { range: "低下", meaning: "安全側", tone: "good" },
      { range: "変化なし", meaning: "中立", tone: "info" },
      { range: "上昇", meaning: "リスク増", tone: "danger" },
    ],
    warning: "リスク低下は同時に期待リターンの低下を伴うことがあります。",
    relatedTerms: ["expectedimpact", "var"],
  },
  {
    key: "sharpe",
    label: "Sharpe",
    shortDescription: "リスク1単位あたりの超過リターン。",
    beginnerDescription: "リターンをリスク（変動の大きさ）で割った効率指標です。高いほど「効率よく」稼げている状態。",
    jarvisRange: [
      { range: "0未満", meaning: "低調", tone: "danger" },
      { range: "0〜1", meaning: "物足りない", tone: "caution" },
      { range: "1〜2", meaning: "良好", tone: "good" },
      { range: "2以上", meaning: "優秀", tone: "good" },
    ],
    goodRange: "1以上",
    dangerRange: "0未満",
    warning: "取引サンプルが少ないと不安定です。期間と併せて評価します。",
    relatedTerms: ["sortino", "cagr"],
  },
  {
    key: "sortino",
    label: "Sortino",
    shortDescription: "下方リスクだけで測ったシャープ。",
    beginnerDescription: "上昇の変動は罰さず、下落の変動だけでリターンを割った指標です。損失回避を重視する評価。",
    jarvisRange: [
      { range: "0未満", meaning: "低調", tone: "danger" },
      { range: "0〜1", meaning: "物足りない", tone: "caution" },
      { range: "1〜2", meaning: "良好", tone: "good" },
      { range: "2以上", meaning: "優秀", tone: "good" },
    ],
    goodRange: "1以上",
    dangerRange: "0未満",
    warning: "上振れを評価しない点がシャープと異なります。両方で見ると解像度が上がります。",
    relatedTerms: ["sharpe", "dd"],
  },
  {
    key: "cvar",
    label: "CVaR",
    shortDescription: "VaRを超えた場合の平均損失（期待ショートフォール）。",
    beginnerDescription: "VaR（想定最大損失）を超えてしまった時に、平均でどれだけ損するかを示す、より保守的なリスク指標です。",
    jarvisRange: [
      { range: "資産の5%以内", meaning: "小さい", tone: "good" },
      { range: "5〜10%", meaning: "標準", tone: "info" },
      { range: "10〜20%", meaning: "大きい", tone: "caution" },
      { range: "20%以上", meaning: "非常に大きい", tone: "danger" },
    ],
    goodRange: "資産の5%以内",
    dangerRange: "資産の20%以上",
    warning: "テールリスク（最悪期の深さ）を表します。VaRより厳しめの目安です。",
    relatedTerms: ["var", "dd"],
  },
  {
    key: "relativevolume",
    label: "相対出来高",
    shortDescription: "当日出来高が20日平均の何倍か。",
    beginnerDescription: "普段と比べて今日どれだけ売買が活発かを倍率で示します。1.0が平常、数値が大きいほど注目度が高い状態。",
    jarvisRange: [
      { range: "1.5倍以上", meaning: "注目", tone: "info" },
      { range: "2倍以上", meaning: "資金流入候補", tone: "good" },
      { range: "3倍以上", meaning: "急騰・急落注意", tone: "danger" },
    ],
    goodRange: "2倍以上",
    dangerRange: "3倍以上",
    warning: "高RSI＋相対出来高急増は過熱（天井圏）の可能性。飛びつきに注意。",
    relatedTerms: ["volume", "volumetrend"],
  },
  {
    key: "volumetrend",
    label: "出来高トレンド",
    shortDescription: "出来高が増加傾向か減少傾向か。",
    beginnerDescription: "直近の出来高が増えているか減っているかの方向感です。関心の高まり/薄れを表します。",
    jarvisRange: [
      { range: "increasing", meaning: "関心上昇", tone: "good" },
      { range: "flat", meaning: "横ばい", tone: "info" },
      { range: "decreasing", meaning: "関心低下", tone: "caution" },
    ],
    warning: "減少トレンドは、上昇があっても持続性に疑問符が付きます。",
    relatedTerms: ["volume", "relativevolume"],
  },
  {
    key: "notificationthreshold",
    label: "Notification Threshold",
    shortDescription: "通知・警告を発火させる条件（しきい値）。",
    beginnerDescription: "どの水準で通知や警告を出すかの基準値です。厳しくすると見逃しにくく、緩めると通知過多を防げます。",
    jarvisRange: [
      { range: "厳しめ", meaning: "見逃し減", tone: "good" },
      { range: "標準", meaning: "既定バランス", tone: "info" },
      { range: "緩め", meaning: "通知過多防止", tone: "caution" },
    ],
    warning: "緩すぎると重大サインを見逃す恐れがあります。標準値からの調整は慎重に。",
    relatedTerms: ["riskgrade", "disciplinescore"],
  },
  {
    key: "advisorscore",
    label: "Advisor Score",
    shortDescription: "7指標を重み付けした0〜100の合成評価。",
    beginnerDescription: "Score/Risk/Backtest/MonteCarlo/Volume/Strategy/Discipline を重み付き合成した総合スコアです。高いほど条件が揃っている目安。",
    jarvisRange: [
      { range: "85以上", meaning: "強気候補", tone: "good" },
      { range: "70〜85", meaning: "買い候補", tone: "good" },
      { range: "60〜70", meaning: "監視", tone: "info" },
      { range: "48未満", meaning: "見送り", tone: "caution" },
    ],
    goodRange: "70以上",
    warning: "重みは Settings で調整できます。合成スコアは判断補助であり投資助言ではありません。",
    relatedTerms: ["adaptivescore", "riskgrade"],
  },
  {
    key: "strongbuy",
    label: "Strong Buy",
    shortDescription: "特に条件が揃った強気候補（Advisor）。",
    beginnerDescription: "合成スコアが高く、押し目圏・低リスク・戦略適合・規律良好が揃った候補です。断定ではなく、少額・段階検討の目安。",
    jarvisRange: [
      { range: "合成85以上", meaning: "強気候補", tone: "good" },
      { range: "Risk S/A", meaning: "低リスク前提", tone: "good" },
    ],
    warning: "強気候補でも集中しすぎは禁物。資金の5〜10%以内が目安です。",
    relatedTerms: ["advisorscore", "riskgrade"],
  },
  {
    key: "watch",
    label: "Watch",
    shortDescription: "監視対象（Advisor）。",
    beginnerDescription: "方向性はあるが、過熱・出来高・タイミング等で即エントリーは見送る監視候補です。押し目や条件成立を待ちます。",
    jarvisRange: [
      { range: "合成60〜70", meaning: "監視", tone: "info" },
      { range: "過熱/出来高過多", meaning: "待機", tone: "caution" },
    ],
    warning: "監視は行動の遅延ではなく、優位性を待つ規律です。",
    relatedTerms: ["advisorscore", "rsi"],
  },
  {
    key: "hold",
    label: "Hold",
    shortDescription: "保有継続（Advisor）。",
    beginnerDescription: "保有中で明確な売買サインがなく、現状維持が妥当な状態です。ルールに沿って監視を続けます。",
    jarvisRange: [{ range: "フラグなし", meaning: "現状維持", tone: "info" }],
    warning: "保有は才能ではなく規律です。損切り/利確ラインの管理を継続してください。",
    relatedTerms: ["disciplinescore", "advisorscore"],
  },
  {
    key: "danger",
    label: "Danger",
    shortDescription: "危険銘柄（Advisor）。",
    beginnerDescription: "損切りライン到達に加え、リスク悪化・出来高減少・規律違反などが重なった状態。防御的な対応を検討します。",
    jarvisRange: [
      { range: "損切到達×複合", meaning: "危険", tone: "danger" },
      { range: "Risk C/D", meaning: "高リスク", tone: "danger" },
    ],
    warning: "危険サインは放置しないこと。感情ではなく規律で判断してください。",
    relatedTerms: ["riskgrade", "disciplinescore"],
  },
  {
    key: "aicomment",
    label: "外部AIコメント",
    shortDescription: "Advisor要約を外部AIへ渡し、回答を保存する参考機能。",
    beginnerDescription: "アプリが生成したプロンプトを外部AIに貼り付け、得られた所見を手動で保存します。自動API接続はせず、APIキーも不要です。",
    jarvisRange: [
      { range: "プロンプト生成", meaning: "コピーして利用", tone: "info" },
      { range: "回答貼り付け", meaning: "手動保存", tone: "info" },
    ],
    warning: "外部AIコメントは参考情報です。売買判断はユーザー自身で行ってください。投資助言ではありません。",
    relatedTerms: ["advisorscore", "riskgrade"],
  },
  {
    key: "stockbt",
    label: "銘柄別BT",
    shortDescription: "銘柄×戦略の過去成績を検証する簡易バックテスト。",
    beginnerDescription: "単一銘柄に戦略条件を当て、過去の価格系列で勝率・PF・最大DD・CAGR・平均保有日数を検証します（軽量版）。",
    jarvisRange: [
      { range: "PF 1.5以上", meaning: "良好", tone: "good" },
      { range: "PF 1未満", meaning: "負け越し", tone: "danger" },
    ],
    warning: "エントリー時点のファンダは現在値近似です。過去実績は将来を保証しません。",
    relatedTerms: ["pf", "dd", "cagr"],
  },
  {
    key: "watchlist",
    label: "Watchlist 自動監視",
    shortDescription: "登録銘柄を定期チェックし条件合致を検出。",
    beginnerDescription: "Score急上昇・RSI過熱/押し目・出来高急増・Advisor判定変化・Risk悪化などを一定間隔で検出し、履歴・通知に残します。完全ローカル。",
    jarvisRange: [
      { range: "監視ON", meaning: "定期検出", tone: "good" },
      { range: "監視OFF", meaning: "手動のみ", tone: "info" },
    ],
    warning: "LINE/ニュース監視は行いません。ブラウザ通知は許可時のみ。判断補助であり投資助言ではありません。",
    relatedTerms: ["advisorchange", "notificationthreshold"],
  },
  {
    key: "btgrade",
    label: "BT Grade",
    shortDescription: "個別銘柄バックテストの総合グレード。",
    beginnerDescription: "銘柄×戦略の過去検証（PF/勝率/最大DD/CAGR/MC）を合成し、S/A+/A/B+/B/C/D で表した評価です。Advisorの合成スコアにも反映されます。",
    jarvisRange: [
      { range: "A+/A", meaning: "過去優位性 高", tone: "good" },
      { range: "B", meaning: "標準", tone: "info" },
      { range: "C/D", meaning: "優位性 低", tone: "caution" },
    ],
    warning: "過去の優位性は将来を保証しません。エントリー時ファンダは現在値近似です。",
    relatedTerms: ["pf", "dd", "expectedvalue"],
  },
  {
    key: "expectedvalue",
    label: "期待値",
    shortDescription: "1取引あたりの平均リターン。",
    beginnerDescription: "過去検証での「勝率×平均利益 −（1−勝率）×平均損失」に相当する、1取引あたりの平均的な損益（%）です。プラスなら優位性の目安。",
    jarvisRange: [
      { range: "プラス", meaning: "優位性あり", tone: "good" },
      { range: "ゼロ近辺", meaning: "中立", tone: "info" },
      { range: "マイナス", meaning: "不利", tone: "danger" },
    ],
    warning: "取引回数が少ないと期待値は不安定です。サンプル数と併せて判断してください。",
    relatedTerms: ["pf", "btgrade"],
  },
  {
    key: "buycandidate",
    label: "Buy Candidate",
    shortDescription: "買い候補（Advisor）。",
    beginnerDescription: "合成スコアが良好で押し目圏にある買い候補です。少額・段階検討の目安であり、断定ではありません。",
    jarvisRange: [
      { range: "合成70以上", meaning: "買い候補", tone: "good" },
      { range: "押し目圏(RSI40-65)", meaning: "タイミング可", tone: "good" },
    ],
    warning: "資金の5〜10%以内・段階エントリーが目安。集中しすぎないこと。",
    relatedTerms: ["strongbuy", "advisorscore"],
  },
  {
    key: "sellcandidate",
    label: "Sell Candidate",
    shortDescription: "売却候補（Advisor）。",
    beginnerDescription: "損切りライン接近・含み損拡大・規律観点で、売却（縮小）を検討すべき保有銘柄です。",
    jarvisRange: [
      { range: "損切接近/到達", meaning: "売却検討", tone: "danger" },
      { range: "含み損拡大", meaning: "縮小検討", tone: "danger" },
    ],
    warning: "感情ではなくルールで判断してください。損失は先送りするほど膨らみます。",
    relatedTerms: ["danger", "disciplinescore"],
  },
  {
    key: "advisorsnapshot",
    label: "Advisor Snapshot",
    shortDescription: "Advisor 判定の保存・履歴・差分。",
    beginnerDescription: "その時点の Advisor 判定（件数・銘柄・合成スコア・使用重み）を保存し、前回との差分（上昇/悪化銘柄）や推移を確認できます。",
    jarvisRange: [
      { range: "composite上昇", meaning: "改善", tone: "good" },
      { range: "composite低下", meaning: "悪化", tone: "caution" },
    ],
    warning: "履歴は localStorage 保持です。定期バックアップを推奨します。",
    relatedTerms: ["advisorscore", "advisorchange"],
  },
  {
    key: "advisorchange",
    label: "Advisor変化",
    shortDescription: "前回判定からの Advisor カテゴリ変化。",
    beginnerDescription: "Strong Buy化・Danger化・損切り候補化・利確候補化など、銘柄の Advisor 判定が前回から変わったことを示します。",
    jarvisRange: [
      { range: "Strong Buy化", meaning: "優位性上昇", tone: "good" },
      { range: "Danger化/損切り化", meaning: "警戒", tone: "danger" },
    ],
    warning: "変化は再評価のきっかけです。断定ではありません。",
    relatedTerms: ["strongbuy", "danger"],
  },
];

const MAP: Record<string, GlossaryTerm> = GLOSSARY.reduce(
  (acc, t) => {
    acc[t.key] = t;
    return acc;
  },
  {} as Record<string, GlossaryTerm>
);

export function getTerm(key: string): GlossaryTerm | undefined {
  return MAP[key];
}

export const toneClass: Record<RangeTone, string> = {
  good: "text-profit",
  info: "text-arc",
  caution: "text-caution",
  danger: "text-danger",
};
